name: CI

on: [push, pull_request]

jobs:
  docker-ci:
    name: Docker-based Lint & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Build Docker image
        run: docker build -t matpvl/matpvl-kp-app .

      - name: Run deploy-lint
        run: docker run --rm -v ${{ github.workspace }}:/app matpvl/matpvl-kp-app uv run invoke deploy-lint

      - name: Run test
        run: docker run --rm -v ${{ github.workspace }}:/app matpvl/matpvl-kp-app uv run invoke test