name: CI

on: [push, pull_request]

jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.meta.outputs.image-tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        run: |
          docker build -t matpvl-image .

  lint:
    name: Lint
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Lint in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/app matpvl-image uv run invoke ruff && \
          docker run --rm -v ${{ github.workspace }}:/app matpvl-image uv run invoke mypy && \
          docker run --rm -v ${{ github.workspace }}:/app matpvl-image uv run invoke vulture && \
          docker run --rm -v ${{ github.workspace }}:/app matpvl-image uv run invoke radon-analysis

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Tests in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/app matpvl-image uv run invoke test